version: '3'
services:
  pgdatabase:
   image: postgres
   restart: always
   environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=my_database
   volumes:
     - ./postgres_data:/var/lib/postgresql/data:rw
     - ./init_scripts:/docker-entrypoint-initdb.d
   ports:
     - 5431:5432
  
  pgadmin:
   image: dpage/pgadmin4
   restart: always
   environment:
     - PGADMIN_DEFAULT_EMAIL=admin@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
   ports:
     - 8080:80
   depends_on:
     - pgdatabase